# Site settings
title: hy43 wiki
url: "https://hy43.github.io"
baseurl: ""
description: >
    hY43 블로그

# My information
email: hyde0401@gmail.com
author: hY43
profile: hY43
github_username: hy43
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: hy43
  shortname: hy43
utterances:
  repo: hy43/hy43.github.io
  issue-term: url
  label: Comment
  branch: master

google_analytics:
  ua: UA-110224147-1

google_adsense:
  client: ca-pub-3675948545737694

blame: "https://github.com/hy43/hy43.github.io/blame/master/_wiki"
edit: "https://github.com/hy43/hy43.github.io/edit/master/_wiki"
issue: "https://github.com/hy43/hy43.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
